/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Elwood with PDBs E630_RL_x64 02-26-2014 18:24 204883"
  #define VERSION_INT   630
#endif

